# Generated by Django 5.0 on 2023-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0002_details_genre_rename_genre_movie_genre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_ids',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.TextField(default=''),
        ),
    ]
