# Generated by Django 5.0 on 2023-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0003_remove_genre_genre_ids_remove_movie_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.TextField(default=''),
        ),
    ]
