# Generated by Django 5.0 on 2023-12-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0004_alter_genre_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.TextField(default=''),
        ),
    ]
