# Generated by Django 5.0 on 2023-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0006_alter_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
