# Generated by Django 5.0 on 2023-12-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0008_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=None),
        ),
    ]
